### ISSUE TITLE
router match mistake, when define named pattern and simple pattern simultaneously

### ISSUE THREAD

**Issue by cssivision** [teambition/trie-mux#1]
```go
package main

import (
    "net/http"
    "github.com/teambition/trie-mux/mux"
)

func main() {
    router := mux.New()
    router.Get("/a/name", func(w http.ResponseWriter, _ *http.Request, _ mux.Params) {
        w.Write([]byte("hello world!\n"))
    })

    router.Get("/:name", func(w http.ResponseWriter, _ *http.Request, _ mux.Params) {
        w.Write([]byte("index\n"))
    })

    http.ListenAndServe(":8080", router)

}
```
i think path `/a` should match pattern `/:name`, but got response `"/a" not implemented`. when match path, simple pattern take precedence over named pattern. https://github.com/teambition/trie-mux/blob/master/trie.go#L132

**Comment by zensh** [comment]
It can't support implicit matching.

You should define `router.Get("/a", handler)`

**Comment by zensh** [comment]
There is [Otherwise](https://github.com/teambition/trie-mux/blob/master/mux/mux.go#L68) mathod  on your demand

**Comment by cssivision** [comment]
In my opinion,  simple pattern take precedence over named pattern, `/a` conflict with `/:a`, if both of them exist, maybe there should be a panic. 

There is other situation
```go
package main

import (
    "net/http"
    "github.com/teambition/trie-mux/mux"
)

func main() {
    router := mux.New()
    router.Get("/a/b", func(w http.ResponseWriter, _ *http.Request, _ mux.Params) {
        w.Write([]byte("hello world!\n"))
    })

    router.Get("/:name/b", func(w http.ResponseWriter, _ *http.Request, _ mux.Params) {
        w.Write([]byte("index\n"))
    })

    http.ListenAndServe(":8080", router)
}
```
`/a/b` is conflict with `/:name/b`, path `/b/b` match `/:name/b`, but it's difficult to find the conflict between them, i can't solve this, so i post a issue.

**Comment by zensh** [comment]
Currently it is enough for practice usage with high performance. Don't make logic intricacy.

**Comment by cssivision** [comment]
Yes, beyond is as wrong as falling short.
